prompt_engine/config/routes.rb
Rails.application.routes.draw do
  get "/prompts/search", to: "prompts#search"
  get "/prompts", to: "prompts#retrieve_all"

  root "prompts#retrieve_all"
  # Catch-all unmatched routes
  match '*unmatched', to: 'application#not_found_routes', via: :all
end

prompt_engine/app/models/activity_log.rb
class ActivityLog < ApplicationRecord
end

prompt_engine/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

prompt_engine/app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end
end

prompt_engine/app/models/prompt.rb
class Prompt < ApplicationRecord
  include Searchable
end

prompt_engine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  def not_found_routes
    render file: Rails.public_path.join('routes_mismatched.html'), status: :not_found, layout: false
  end
end

prompt_engine/app/controllers/prompts_controller.rb
require 'will_paginate/array' 

class PromptsController < ApplicationController
  before_action :setter
  after_action :track_search_activity, only: [:search]

  attr_reader :prompt_service

  def setter(prompt_service = PromptService.new)
    @prompt_service = prompt_service
  end

  # GET /prompts
  def retrieve_all
    begin
      # Fetch the list of prompts using the provided page parameter.
      @prompts = prompt_service.list_prompts(params[:page])
      render "index", status: (@prompts.blank? ? :not_found : :ok)
    rescue PromptServiceException => error
      flash.now[:alert] = "We encountered a temporary issue while retrieving prompts. Please try again soon."
      render 'index', status: :internal_server_error
    end
  end

  # GET /prompts/search 
  def search
    begin
      unless params[:query].present?
        redirect_to root_path
      end
      @prompts = prompt_service.perform_search(params[:query], params[:page])
    rescue PromptServiceException => error
      flash.now[:alert] = "Internal error occured. Please try again."
    end
    # sending status 'ok' to control view and flashing errors, 
    # can be changed based on view choices
    render "index", status: :ok
  end

  private
  def track_search_activity
    PromptSearchTrackerJob.perform_later(params[:query])
  end
end

prompt_engine/app/helpers/application_helper.rb
module ApplicationHelper
end

prompt_engine/app/helpers/prompt_helper.rb
module PromptHelper
  def parse_data(search_results)
    hits = JSON.parse(search_results.to_json)['hits']['hits']
    data = hits.map { |hit| hit['_source']['data'] }
  end

  def paginate(data, page)
    data.paginate(page: page, per_page: $PAGINATION_SIZE )
  end

  def build_bulk_request_body(prompts)
    # Iterate over prompts
    bulk_request_body = prompts.map do |prompt|
      # Build index metadata
      index_metadata = { index: { _index: 'prompts' } }
      # Build bulk request body
      [index_metadata.to_json, { 'data': prompt , 'length': prompt.length}.to_json].join("\n")
    end

    return bulk_request_body
  end
end

prompt_engine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AudemicPromptEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'prompts', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

prompt_engine/app/views/prompts/_flash_messages.html.erb
<%# Partial for flash messages %>

<% flash.each do |key, message| %>
  <% if key == 'warn' %>
    <div class="prompt_warn">
      <span class="prompt_alert_closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      <%= message %>
    </div>
  <% else %>
    <div class="prompt_alert">
      <span class="prompt_alert_closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      <%= message %>
    </div>
  <% end %>
<% end %>

prompt_engine/app/views/prompts/_form.html.erb
<%# Search prompt form partial %>

<%= form_tag(prompts_search_path, method: :get) do %>
  <div class="col-12 col-s-12">
    <%= text_field_tag(:query, params[:query], placeholder: "Enter your search query", required: true) %>
    <% unless @prompts.nil? %>
      <span class="total_prompts"><%= @prompts.total_entries %> results</span>
    <% end %>
    <div class="responsive-text" id="responsiveText">Search Keywords like: (A potrait, Beautiful)</div>
  </div>
  <div class="col-12 col-s-12 submit_div">
    <%= submit_tag('Search') %>
  </div>
<% end %>

prompt_engine/app/views/prompts/_prompts.html.erb
<%# Partial for resulted prompts for searched keyword %>

<% if !flash.present? %>
  <% if @prompts.present? %>
    <h3>Search Results:</h3>
    <table class="prompt_table">
      <tr></tr>
      <% @prompts.compact.each do |prompt| %>
        <tr><td><%= prompt %></td></tr>
      <% end %>
    </table>
  <% else %>
    <p>No results found.</p>
  <% end %>
<% end %>

prompt_engine/app/views/prompts/index.html.erb
<%= render 'flash_messages' %>

<div class="header">
  <center><h1>Search Prompts</h1></center>
</div>

<div class="row search_page_body">
  <%= render 'form' %>

  <div class="col-12 col-s-12 prompts_list">
    <%= render 'prompts' %>
  </div>
</div>

<% if @prompts.present? %>
  <div class="text-center my-4">
    <div role="navigation" aria-label="Pagination" class="px-3 py-2 mx-2 text-gray-700 no-underline bg-white rounded-lg">
      <div class="flickr_pagination">
        <div class="py-4">
          <%= will_paginate @prompts %>
        </div>
      </div>
    </div>
  </div>
<% end %>